import { PLUGIN_NAMES } from "./constants";
export const DEFAULT_SETTINGS = {
  disableBeforeInput: false,
  emptyEditor: false,
  isRichText: true,
  measureTypingPerf: false,
  showTreeView: true,
  enableAutoFocusPlugin: true,
  enableAutoEmbedPlugin: true,
  enableClearEditorPlugin: true,
  enableClickableLinkPlugin: true,
  enableCodeActionMenuPlugin: true,
  enableCollapsiblePlugin: true,
  enableDragDropPastePlugin: true,
  enableDraggableBlockPlugin: true,
  enableExcalidrawPlugin: true,
  enableFloatingLinkEditorPlugin: true,
  enableFloatingTextFormatToolbarPlugin: true,
  enableHintPlugin: true,
  enableHorizontalRulePlugin: true,
  enableImagesPlugin: true,
  enableLayoutPlugin: true,
  enableLexicalAutoLinkPlugin: true,
  enableLexicalOnChangePlugin: true,
  enableLinkPlugin: true,
  enableLinkWithMetaDataPlugin: true,
  enableListPlugin: true,
  enableMarkdownShortcutPlugin: true,
  enablePollPlugin: true,
  enableShortcutsPlugin: true,
  enableSlashCommand: true,
  enableStepperPlugin: true,
  enableTabFocusPlugin: true,
  enableTabIndentationPlugin: true,
  enableTableCellActionMenuPlugin: true,
  enableTableCellResizerPlugin: true,
  enableTableHoverActionsPlugin: true,
  enableTablePlugin: true,
  enableTableOfContentsPlugin: true,
  enableTwitterPlugin: true,
  enableYouTubePlugin: true,
  enableToolbarPlugin: true,
  enableHistoryPlugin: true,
  enableCheckListPlugin: true,
  enableCodeHighlightPlugin: true,
} as const;

import {
  Pilcrow,
  Heading1,
  Heading2,
  Heading3,
  Table,
  OctagonX,
  DraftingCompass,
  ListOrdered,
  List,
  ListCheck,
  QuoteIcon,
  SquarePenIcon,
  Code2,
  Minus,
  Youtube,
  Twitter,
  ImageIcon,
  ImagePlayIcon,
  Columns2,
  Columns3,
  Columns4,
  StepForward,
  AlertCircle,
  FlipHorizontal2,
  SquareChevronRight,
} from "lucide-react";

export const PLUGIN_CONFIG = {
  [PLUGIN_NAMES.PARAGRAPH]: {
    label: PLUGIN_NAMES.PARAGRAPH,
    icon: Pilcrow,
    keywords: ["normal", "paragraph", "p", "text"],
    desc: "Just start writing with plain text",
  },
  [PLUGIN_NAMES.HEADING_1]: {
    label: PLUGIN_NAMES.HEADING_1,
    icon: Heading1,
    keywords: ["heading", "header", "h1"],
    desc: "Big section heading",
  },
  [PLUGIN_NAMES.HEADING_2]: {
    label: PLUGIN_NAMES.HEADING_2,
    icon: Heading2,
    keywords: ["heading", "header", "h2"],
    desc: "Medium section heading",
  },
  [PLUGIN_NAMES.HEADING_3]: {
    label: PLUGIN_NAMES.HEADING_3,
    icon: Heading3,
    keywords: ["heading", "header", "h3"],
    desc: "Small section heading",
  },
  [PLUGIN_NAMES.TABLE]: {
    label: PLUGIN_NAMES.TABLE,
    icon: Table,
    keywords: ["table", "grid", "spreadsheet", "rows", "columns"],
    desc: "Add simple table content to your blog.",
  },
  [PLUGIN_NAMES.HINT]: {
    label: PLUGIN_NAMES.HINT,
    icon: OctagonX,
    keywords: ["hint", "note", "info", "alert", "success", "warning", "error"],
    desc: "Add a hint to your content.",
  },
  [PLUGIN_NAMES.EXCALIDRAW]: {
    label: PLUGIN_NAMES.EXCALIDRAW,
    icon: DraftingCompass,
    keywords: ["excalidraw", "diagram", "drawing"],
    desc: "Create diagrams and drawings",
  },
  [PLUGIN_NAMES.NUMBERED_LIST]: {
    label: PLUGIN_NAMES.NUMBERED_LIST,
    icon: ListOrdered,
    keywords: ["numbered list", "ordered list", "ol"],
    desc: "Create list with number",
  },
  [PLUGIN_NAMES.BULLETED_LIST]: {
    label: PLUGIN_NAMES.BULLETED_LIST,
    icon: List,
    keywords: ["bulleted list", "unordered list", "ul"],
    desc: "Create list with Bulleted",
  },
  [PLUGIN_NAMES.CHECK_LIST]: {
    label: PLUGIN_NAMES.CHECK_LIST,
    icon: ListCheck,
    keywords: ["check list", "todo list"],
    desc: "Track tasks with to-do list.",
  },
  [PLUGIN_NAMES.QUOTE]: {
    label: PLUGIN_NAMES.QUOTE,
    icon: QuoteIcon,
    keywords: ["block quote"],
    desc: "Capture Quote",
  },
  [PLUGIN_NAMES.POLL]: {
    label: PLUGIN_NAMES.POLL,
    icon: SquarePenIcon,
    keywords: ["pool", "vote", "survey"],
    desc: "Add pool to take people votes.",
  },
  [PLUGIN_NAMES.CODE]: {
    label: PLUGIN_NAMES.CODE,
    icon: Code2,
    keywords: ["javascript", "python", "js", "codeblock"],
    desc: "Add block of code.",
  },
  [PLUGIN_NAMES.DIVIDER]: {
    label: PLUGIN_NAMES.DIVIDER,
    icon: Minus,
    keywords: ["horizontal rule", "divider", "hr"],
    desc: "Visually divide blocks",
  },
  [PLUGIN_NAMES.YOUTUBE]: {
    label: PLUGIN_NAMES.YOUTUBE,
    icon: Youtube,
    keywords: ["youtube", "video"],
    desc: "Embedded YouTube videos",
  },
  [PLUGIN_NAMES.TWITTER]: {
    label: PLUGIN_NAMES.TWITTER,
    icon: Twitter,
    keywords: ["twitter", "tweet", "x"],
    desc: "Embedded Tweets",
  },
  [PLUGIN_NAMES.IMAGE]: {
    label: PLUGIN_NAMES.IMAGE,
    icon: ImageIcon,
    keywords: ["image", "photo", "picture", "file", "img"],
    desc: "Upload or embed with a link",
  },
  [PLUGIN_NAMES.GIFS]: {
    label: PLUGIN_NAMES.GIFS,
    icon: ImagePlayIcon,
    keywords: ["gif", "gifs", "videos", "short video"],
    desc: "Insert a GIF video",
  },
  [PLUGIN_NAMES.COLLAPSIBLE]: {
    label: PLUGIN_NAMES.COLLAPSIBLE,
    icon: StepForward,
    keywords: ["collapse", "collapsible", "toggle"],
    desc: "Toggles can hide and show content inside.",
  },
  [PLUGIN_NAMES.TWO_COLUMNS]: {
    label: PLUGIN_NAMES.TWO_COLUMNS,
    icon: Columns2,
    keywords: ["columns", "flex", "row", "layout", "grid"],
    desc: "Divide your content into 2 container.",
  },
  [PLUGIN_NAMES.THREE_COLUMNS]: {
    label: PLUGIN_NAMES.THREE_COLUMNS,
    icon: Columns3,
    keywords: ["3columns", "3", "flex", "row", "layout", "grid"],
    desc: "Divide your content into 3 container.",
  },
  [PLUGIN_NAMES.FOUR_COLUMNS]: {
    label: PLUGIN_NAMES.FOUR_COLUMNS,
    icon: Columns4,
    keywords: ["4columns", "4", "flex", "row", "layout", "grid"],
    desc: "Divide your content into 4 container.",
  },
  [PLUGIN_NAMES.STEPPER]: {
    label: PLUGIN_NAMES.STEPPER,
    icon: StepForward,
    keywords: ["stepper", "step", "lines", "routes", "docs", "number"],
    desc: "Stepper with descriptions for each step.",
  },
  [PLUGIN_NAMES.HORIZONTAL_RULE]: {
    label: "Horizontal Rule",
    icon: FlipHorizontal2,
    keywords: ["horizontal rule", "divider", "hr"],
    desc: "Visually divide blocks",
  },
  [PLUGIN_NAMES.MEDIA]: {
    label: "Media",
    icon: Image,
    keywords: ["image", "photo", "picture", "file", "img"],
    desc: "Upload or embed with a link",
  },
  [PLUGIN_NAMES.TWO_COLUMNS_EQUAL]: {
    label: "2 columns (equal width)",
    icon: Columns2,
    keywords: ["columns", "flex", "row", "layout", "grid"],
    desc: "Divide your content into 2 equal-width containers.",
  },
  [PLUGIN_NAMES.THREE_COLUMNS_EQUAL]: {
    label: "3 columns (equal width)",
    icon: Columns3,
    keywords: ["3columns", "3", "flex", "row", "layout", "grid"],
    desc: "Divide your content into 3 equal-width containers.",
  },
  [PLUGIN_NAMES.FOUR_COLUMNS_EQUAL]: {
    label: "4 columns (equal width)",
    icon: Columns4,
    keywords: ["4columns", "4", "flex", "row", "layout", "grid"],
    desc: "Divide your content into 4 equal-width containers.",
  },
  [PLUGIN_NAMES.TWO_COLUMNS_25_75]: {
    label: "2 columns (25% - 75%)",
    icon: Columns2,
    keywords: ["columns", "flex", "row", "layout", "grid"],
    desc: "Divide your content into 2 containers with 25% and 75% width.",
  },
  [PLUGIN_NAMES.COLLAPSIBLE_CONTAINER]: {
    label: "Collapsible container",
    icon: SquareChevronRight,
    keywords: ["collapse", "collapsible", "toggle"],
    desc: "Toggles can hide and show content inside.",
  },
};

// These are mutated in setupEnv
export const INITIAL_SETTINGS: Record<SettingName, boolean> = {
  ...DEFAULT_SETTINGS,
};

export type SettingName = keyof typeof DEFAULT_SETTINGS;

export type Settings = typeof INITIAL_SETTINGS;

/**
 * make all to constants use same in slashcommands
 * do same op for nav bar list
 */
