import { PLUGIN_NAMES } from "./constants";

import {
	Pilcrow,
	Heading1,
	Heading2,
	Heading3,
	Table,
	OctagonX,
	DraftingCompass,
	ListOrdered,
	List,
	ListCheck,
	QuoteIcon,
	SquarePenIcon,
	Code2,
	Minus,
	Youtube,
	Twitter,
	ImageIcon,
	ImagePlayIcon,
	Columns2,
	Columns3,
	Columns4,
	StepForward,
	AlertCircle,
	FlipHorizontal2,
	SquareChevronRight,
} from "lucide-react";
import { SHORTCUTS } from "./plugins/ShortcutsPlugin/shortcuts";

export const PLUGIN_CONFIG = {
	[PLUGIN_NAMES.PARAGRAPH]: {
		isEnabled: true,
		label: PLUGIN_NAMES.PARAGRAPH,
		icon: Pilcrow,
		keywords: ["normal", "paragraph", "p", "text"],
		desc: "Just start writing with plain text",
		keyboardShortcut: undefined,
		showInSlashCommand: true,
		showInInsertList: true,
	},
	[PLUGIN_NAMES.HEADING_1]: {
		isEnabled: true,
		label: PLUGIN_NAMES.HEADING_1,
		icon: Heading1,
		keywords: ["heading", "header", "h1"],
		desc: "Big section heading",
		keyboardShortcut: SHORTCUTS.HEADING1,
		showInSlashCommand: true,
		showInInsertList: true,
	},
	[PLUGIN_NAMES.HEADING_2]: {
		isEnabled: true,
		label: PLUGIN_NAMES.HEADING_2,
		icon: Heading2,
		keywords: ["heading", "header", "h2"],
		desc: "Medium section heading",
		keyboardShortcut: SHORTCUTS.HEADING2,
		showInSlashCommand: true,
		showInInsertList: true,
	},
	[PLUGIN_NAMES.HEADING_3]: {
		isEnabled: true,
		label: PLUGIN_NAMES.HEADING_3,
		icon: Heading3,
		keywords: ["heading", "header", "h3"],
		desc: "Small section heading",
		keyboardShortcut: SHORTCUTS.HEADING3,
		showInSlashCommand: true,
		showInInsertList: true,
	},
	[PLUGIN_NAMES.TABLE]: {
		isEnabled: true,
		label: PLUGIN_NAMES.TABLE,
		icon: Table,
		keywords: ["table", "grid", "spreadsheet", "rows", "columns"],
		desc: "Add simple table content to your blog.",
		keyboardShortcut: undefined,
		showInSlashCommand: true,
		showInInsertList: true,
	},
	[PLUGIN_NAMES.HINT]: {
		isEnabled: true,
		label: PLUGIN_NAMES.HINT,
		icon: OctagonX,
		keywords: ["hint", "note", "info", "alert", "success", "warning", "error"],
		desc: "Add a hint to your content.",
		keyboardShortcut: undefined,
		showInSlashCommand: true,
		showInInsertList: true,
	},
	[PLUGIN_NAMES.EXCALIDRAW]: {
		isEnabled: true,
		label: PLUGIN_NAMES.EXCALIDRAW,
		icon: DraftingCompass,
		keywords: ["excalidraw", "diagram", "drawing"],
		desc: "Create diagrams and drawings",
		keyboardShortcut: undefined,
		showInSlashCommand: true,
		showInInsertList: true,
	},
	[PLUGIN_NAMES.NUMBERED_LIST]: {
		isEnabled: true,
		label: PLUGIN_NAMES.NUMBERED_LIST,
		icon: ListOrdered,
		keywords: ["numbered list", "ordered list", "ol"],
		desc: "Create list with number",
		keyboardShortcut: SHORTCUTS.NUMBERED_LIST,
		showInSlashCommand: true,
		showInInsertList: true,
	},
	[PLUGIN_NAMES.BULLETED_LIST]: {
		isEnabled: true,
		label: PLUGIN_NAMES.BULLETED_LIST,
		icon: List,
		keywords: ["bulleted list", "unordered list", "ul"],
		desc: "Create list with Bulleted",
		keyboardShortcut: SHORTCUTS.BULLET_LIST,
		showInSlashCommand: true,
		showInInsertList: true,
	},
	[PLUGIN_NAMES.CHECK_LIST]: {
		isEnabled: true,
		label: PLUGIN_NAMES.CHECK_LIST,
		icon: ListCheck,
		keywords: ["check list", "todo list"],
		desc: "Track tasks with to-do list.",
		keyboardShortcut: SHORTCUTS.CHECK_LIST,
		showInSlashCommand: true,
		showInInsertList: true,
	},
	[PLUGIN_NAMES.QUOTE]: {
		isEnabled: true,
		label: PLUGIN_NAMES.QUOTE,
		icon: QuoteIcon,
		keywords: ["block quote"],
		desc: "Capture Quote",
		keyboardShortcut: SHORTCUTS.QUOTE,
		showInSlashCommand: true,
		showInInsertList: true,
	},
	[PLUGIN_NAMES.POLL]: {
		isEnabled: true,
		label: PLUGIN_NAMES.POLL,
		icon: SquarePenIcon,
		keywords: ["pool", "vote", "survey"],
		desc: "Add pool to take people votes.",
		keyboardShortcut: undefined,
		showInSlashCommand: true,
		showInInsertList: true,
	},
	[PLUGIN_NAMES.CODE]: {
		isEnabled: true,
		label: PLUGIN_NAMES.CODE,
		icon: Code2,
		keywords: ["javascript", "python", "js", "codeblock"],
		desc: "Add block of code.",
		keyboardShortcut: SHORTCUTS.CODE_BLOCK,
		showInSlashCommand: true,
		showInInsertList: true,
	},
	[PLUGIN_NAMES.DIVIDER]: {
		isEnabled: true,
		label: PLUGIN_NAMES.DIVIDER,
		icon: Minus,
		keywords: ["horizontal rule", "divider", "hr"],
		desc: "Visually divide blocks",
		keyboardShortcut: undefined,
		showInSlashCommand: true,
		showInInsertList: true,
	},
	[PLUGIN_NAMES.YOUTUBE]: {
		isEnabled: true,
		label: PLUGIN_NAMES.YOUTUBE,
		icon: Youtube,
		keywords: ["youtube", "video"],
		desc: "Embedded YouTube videos",
		keyboardShortcut: undefined,
		showInSlashCommand: true,
		showInInsertList: true,
	},
	[PLUGIN_NAMES.TWITTER]: {
		isEnabled: true,
		label: PLUGIN_NAMES.TWITTER,
		icon: Twitter,
		keywords: ["twitter", "tweet", "x"],
		desc: "Embedded Tweets",
		keyboardShortcut: undefined,
		showInSlashCommand: true,
		showInInsertList: true,
	},
	[PLUGIN_NAMES.IMAGE]: {
		isEnabled: true,
		label: PLUGIN_NAMES.IMAGE,
		icon: ImageIcon,
		keywords: ["image", "photo", "picture", "file", "img"],
		desc: "Upload or embed with a link",
		keyboardShortcut: undefined,
		showInSlashCommand: true,
		showInInsertList: true,
	},
	[PLUGIN_NAMES.GIFS]: {
		isEnabled: true,
		label: PLUGIN_NAMES.GIFS,
		icon: ImagePlayIcon,
		keywords: ["gif", "gifs", "videos", "short video"],
		desc: "Insert a GIF video",
		keyboardShortcut: undefined,
		showInSlashCommand: true,
		showInInsertList: true,
	},
	[PLUGIN_NAMES.COLLAPSIBLE]: {
		isEnabled: true,
		label: PLUGIN_NAMES.COLLAPSIBLE,
		icon: StepForward,
		keywords: ["collapse", "collapsible", "toggle"],
		desc: "Toggles can hide and show content inside.",
		keyboardShortcut: undefined,
		showInSlashCommand: true,
		showInInsertList: true,
	},
	[PLUGIN_NAMES.TWO_COLUMNS]: {
		isEnabled: true,
		label: PLUGIN_NAMES.TWO_COLUMNS,
		icon: Columns2,
		keywords: ["columns", "flex", "row", "layout", "grid"],
		desc: "Divide your content into 2 container.",
		keyboardShortcut: undefined,
		showInSlashCommand: true,
		showInInsertList: true,
	},
	[PLUGIN_NAMES.THREE_COLUMNS]: {
		isEnabled: true,
		label: PLUGIN_NAMES.THREE_COLUMNS,
		icon: Columns3,
		keywords: ["3columns", "3", "flex", "row", "layout", "grid"],
		desc: "Divide your content into 3 container.",
		keyboardShortcut: undefined,
		showInSlashCommand: true,
		showInInsertList: true,
	},
	[PLUGIN_NAMES.FOUR_COLUMNS]: {
		isEnabled: true,
		label: PLUGIN_NAMES.FOUR_COLUMNS,
		icon: Columns4,
		keywords: ["4columns", "4", "flex", "row", "layout", "grid"],
		desc: "Divide your content into 4 container.",
		keyboardShortcut: undefined,
		showInSlashCommand: true,
		showInInsertList: true,
	},
	[PLUGIN_NAMES.STEPPER]: {
		isEnabled: true,
		icon: StepForward,
		keywords: ["stepper", "step", "lines", "routes", "docs", "number"],
		desc: "Stepper with descriptions for each step.",
		keyboardShortcut: undefined,
		showInSlashCommand: true,
		showInInsertList: true,
	},
	[PLUGIN_NAMES.HORIZONTAL_RULE]: {
		isEnabled: true,
		label: "Horizontal Rule",
		icon: FlipHorizontal2,
		keywords: ["horizontal rule", "divider", "hr"],
		desc: "Visually divide blocks",
		keyboardShortcut: undefined,
		showInSlashCommand: true,
		showInInsertList: true,
	},
	[PLUGIN_NAMES.MEDIA]: {
		isEnabled: true,
		label: "Media",
		icon: ImageIcon,
		keywords: ["image", "photo", "picture", "file", "img"],
		desc: "Upload or embed with a link",
		keyboardShortcut: undefined,
		showInSlashCommand: true,
		showInInsertList: true,
	},
	[PLUGIN_NAMES.TWO_COLUMNS_EQUAL]: {
		isEnabled: true,
		label: "2 columns (equal width)",
		icon: Columns2,
		keywords: ["columns", "flex", "row", "layout", "grid"],
		desc: "Divide your content into 2 equal-width containers.",
		keyboardShortcut: undefined,
		showInSlashCommand: true,
		showInInsertList: true,
	},
	[PLUGIN_NAMES.THREE_COLUMNS_EQUAL]: {
		isEnabled: true,
		label: "3 columns (equal width)",
		icon: Columns3,
		keywords: ["3columns", "3", "flex", "row", "layout", "grid"],
		desc: "Divide your content into 3 equal-width containers.",
		keyboardShortcut: undefined,
		showInSlashCommand: true,
		showInInsertList: true,
	},
	[PLUGIN_NAMES.FOUR_COLUMNS_EQUAL]: {
		isEnabled: true,
		label: "4 columns (equal width)",
		icon: Columns4,
		keywords: ["4columns", "4", "flex", "row", "layout", "grid"],
		desc: "Divide your content into 4 equal-width containers.",
		keyboardShortcut: undefined,
		showInSlashCommand: true,
		showInInsertList: true,
	},
	[PLUGIN_NAMES.TWO_COLUMNS_25_75]: {
		isEnabled: true,
		label: "2 columns (25% - 75%)",
		icon: Columns2,
		keywords: ["columns", "flex", "row", "layout", "grid"],
		desc: "Divide your content into 2 containers with 25% and 75% width.",
		keyboardShortcut: undefined,
		showInSlashCommand: true,
		showInInsertList: true,
	},
	[PLUGIN_NAMES.COLLAPSIBLE_CONTAINER]: {
		isEnabled: true,
		label: "Collapsible container",
		icon: SquareChevronRight,
		keywords: ["collapse", "collapsible", "toggle"],
		desc: "Toggles can hide and show content inside.",
		keyboardShortcut: undefined,
		showInSlashCommand: true,
		showInInsertList: true,
	},
	[PLUGIN_NAMES.TABLE_OF_CONTENTS]: {
		isEnabled: true,
		showInSlashCommand: false,
		showInInsertList: false,
		label: "",
		icon: SquareChevronRight,
		keywords: [],
		desc: "",
		keyboardShortcut: undefined,
	},
	[PLUGIN_NAMES.SLASH_COMMAND]: {
		isEnabled: true,
		showInSlashCommand: false,
		showInInsertList: false,
		label: "",
		icon: SquareChevronRight,
		keywords: [],
		desc: "",
		keyboardShortcut: undefined,
	},
	[PLUGIN_NAMES.AUTO_FOCUS]: {
		isEnabled: true,
		showInSlashCommand: false,
		showInInsertList: false,
		label: "",
		icon: SquareChevronRight,
		keywords: [],
		desc: "",
		keyboardShortcut: undefined,
	},
};
export type pluginConfig = typeof PLUGIN_CONFIG;
export type PluginConfigured = keyof typeof PLUGIN_NAMES;
