import type { Metadata } from "next";
import { Inter, Source_Code_Pro, Source_Serif_4 } from "next/font/google";
import "./globals.css";
import Background from "@/components/shared/Background";
import { ThemeProvider } from "@/providers/ThemeProvider";
import { Toaster } from "@/components/ui/toaster";
import Nav from "@/components/shared/nav";
import {
	SidebarProvider as SidebarProviderShadcn,
	SidebarTrigger,
} from "@/components/ui/sidebar";
import { SidebarProvider } from "@/context/SidebarContext";
import { Sidebar } from "@/components/sidebar/Sidebar";

const inter = Inter({
	variable: "--font-inter",
	subsets: ["latin"],
});

const sourceCodePro = Source_Code_Pro({
	variable: "--font-code",
	subsets: ["latin"],
});

const sourceSerif4 = Source_Serif_4({
	variable: "--font-source-serif",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${inter.variable} ${sourceCodePro.variable} ${sourceSerif4.variable} antialiased  relative var(--background)`}
			>
				<main className="font-source-serif ">
					<ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
						<SidebarProvider className="flex">
							<Sidebar />
							<main className="flex-1">
								<Nav />
								{children}
							</main>
							<Background />
							<Toaster />
						</SidebarProvider>
					</ThemeProvider>
				</main>
			</body>
		</html>
	);
}
