import type { Metadata } from "next";
import { Inter, Source_Code_Pro, Source_Serif_4 } from "next/font/google";
import "./globals.css";
import Background from "@/components/shared/Background";
import { ThemeProvider } from "@/providers/ThemeProvider";
import { Toaster } from "@/components/ui/toaster";
import { Toaster as Sonner } from "@/components/ui/sonner";
import { SidebarProvider } from "@/context/SidebarContext";
import { Sidebar } from "@/components/sidebar/Sidebar";
import SidePanelLayout from "@/components/sidebar/panelLayout";
import { SessionProvider } from "next-auth/react";
import QueryProvider from "@/providers/QueryProvider";
const inter = Inter({
	variable: "--font-inter",
	subsets: ["latin"],
});

const sourceCodePro = Source_Code_Pro({
	variable: "--font-code",
	subsets: ["latin"],
});

const sourceSerif4 = Source_Serif_4({
	variable: "--font-source-serif",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export const experimental_ppr = true;

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${inter.variable} ${sourceCodePro.variable} ${sourceSerif4.variable} font-source-serif antialiased  relative var(--background)`}
			>
				<SessionProvider>
					<ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
						<QueryProvider>
							<SidebarProvider>
								<SidePanelLayout>{children}</SidePanelLayout>
								<Background />
								<Toaster />
								<Sonner />
							</SidebarProvider>
						</QueryProvider>
					</ThemeProvider>
				</SessionProvider>
			</body>
		</html>
	);
}
