import {
    FaAmazon, FaGoogle, FaBuilding, FaMicrosoft, FaApple, FaFacebook, FaSalesforce, FaPaypal, FaDocker, FaAtlassian, FaBitbucket, FaGithub, FaGitlab, FaSlack, FaDropbox, FaTrello, FaShopify, FaWordpress, FaStripe
} from "react-icons/fa";

import {
    SiFlipkart, SiTata, SiInfosys, SiWipro, SiHcl, SiZoho, SiSamsung, SiNvidia, SiCisco, SiUber, SiAirbnb, SiSpotify, SiOracle, SiDell, SiHp, SiLenovo, SiVmware, SiOpenai, SiDigitalocean, SiCloudflare, SiFastly, SiHeroku,
     SiVercel, SiNetlify, SiKubernetes, SiIntel, SiAccenture, SiCognizant, SiSap, SiTwilio, SiHubspot, SiPagerduty, SiElastic, SiMongodb, SiSnowflake, SiDatabricks, SiCloudera, SiPaloaltonetworks, SiOkta,SiF5, SiNokia, SiEricsson,
      SiAlibabacloud, SiMercadopago, SiRakuten, SiNaver, SiMailchimp, SiSendgrid, SiBrave, SiOpera, SiEclipseide, SiJetbrains, SiPostman, SiSwagger, SiFigma, SiSketch, SiAdobexd, SiInvision, SiJira, SiConfluence, SiAsana, SiAirtable,
       SiNotion, SiEvernote, SiGrammarly, SiDuolingo, SiUdemy, SiCoursera, SiKhanacademy, SiPluralsight, SiLinkedin, SiGlassdoor, SiIndeed, SiUpwork, SiFreelancer, SiFiverr, SiStackoverflow, SiMedium, SiQuora, SiHashnode, SiDevdotto,
        SiCodepen, SiReplit, SiGlitch, SiCodesandbox, SiLeetcode, SiHackerrank, SiAlgolia, SiAuth0, SiFirebase, SiSupabase, SiHasura, SiGraphql, SiApache, SiNginx, SiRedis, SiRabbitmq, SiPrometheus, SiGradle, SiGnubash, SiGit, SiJquery, SiRedux, SiWebpack, SiBabel, SiEslint, SiPrettier, SiJest, SiCypress, SiPuppeteer, SiStorybook, SiLoom, SiZoom, SiGoogledrive, SiTorbrowser, SiProtonmail, SiTutanota, SiBitcoin, SiEthereum, SiBinance, SiCoinbase, SiRipple, SiPolkadot, SiSolana, SiChainlink, SiAlgorand, SiStellar, SiMonero, SiZcash
} from "react-icons/si";


const companies = [
    // Top Companies (Cloud, Tech, Dev Tools)
    { label: "Amazon", icon: FaAmazon },
    { label: "Google", icon: FaGoogle },
    { label: "Apple", icon: FaApple },
    { label: "Uber", icon: SiUber },
    { label: "Microsoft", icon: FaMicrosoft },
    { label: "FlipKart", icon: SiFlipkart },
    { label: "Facebook", icon: FaFacebook },
    { label: "PayPal", icon: FaPaypal },
    { label: "Airbnb", icon: SiAirbnb },
    { label: "Atlassian", icon: FaAtlassian },
    { label: "Docker", icon: FaDocker },
    { label: "Stripe", icon: FaStripe },
    { label: "Spotify", icon: SiSpotify },
    { label: "Oracle", icon: SiOracle },
    { label: "GitHub", icon: FaGithub },
    { label: "GitLab", icon: FaGitlab },
    { label: "Salesforce", icon: FaSalesforce },
    { label: "Slack", icon: FaSlack },
    { label: "Shopify", icon: FaShopify },
    { label: "Trello", icon: FaTrello },
    { label: "Dropbox", icon: FaDropbox },
    { label: "Cisco", icon: SiCisco },
    { label: "NVIDIA", icon: SiNvidia },
    { label: "Intel", icon: SiIntel },
    { label: "Samsung", icon: SiSamsung },
    { label: "Dell", icon: SiDell },
    { label: "HP", icon: SiHp },
    { label: "Lenovo", icon: SiLenovo },
    { label: "VMware", icon: SiVmware },
    { label: "DigitalOcean", icon: SiDigitalocean },
    { label: "Cloudflare", icon: SiCloudflare },
    { label: "Heroku", icon: SiHeroku },
    { label: "Vercel", icon: SiVercel },
    { label: "Netlify", icon: SiNetlify },
    { label: "Kubernetes", icon: SiKubernetes },
    { label: "IBM", icon: FaBuilding },
  
    // Regional Tech Companies
    { label: "TCS", icon: SiTata },
    { label: "Infosys", icon: SiInfosys },
    { label: "Wipro", icon: SiWipro },
    { label: "HCL", icon: SiHcl },
    { label: "Tech Mahindra", icon: FaBuilding },
    { label: "Zoho", icon: SiZoho },
    { label: "Freshworks", icon: FaBuilding },
  
    // Developer Tools & Services
    { label: "JetBrains", icon: SiJetbrains },
    { label: "Postman", icon: SiPostman },
    { label: "Figma", icon: SiFigma },
    { label: "Swagger", icon: SiSwagger },
    { label: "GitLab", icon: FaGitlab },
    { label: "Bitbucket", icon: FaBitbucket },
  
    // Cloud & DevOps Services
    { label: "Alibaba Cloud", icon: SiAlibabacloud },
    { label: "OVHcloud", icon: FaBuilding },
    { label: "Linode", icon: FaBuilding },
    { label: "Scaleway", icon: FaBuilding },
  
    // Cybersecurity
    { label: "Kaspersky", icon: FaBuilding },
    { label: "Norton", icon: FaBuilding },
    { label: "Malwarebytes", icon: FaBuilding },
  
    // AI/ML
    { label: "DeepMind", icon: FaBuilding },
    { label: "OpenCV", icon: FaBuilding },
    { label: "Hugging Face", icon: FaBuilding },
  
    // Blockchain
    { label: "Binance", icon: SiBinance },
    { label: "Coinbase", icon: SiCoinbase },
    { label: "Polkadot", icon: SiPolkadot },
  
    // Regional Tech Companies (continued)
    { label: "MercadoLibre", icon: SiMercadopago },
    { label: "Rakuten", icon: SiRakuten },
    { label: "Naver", icon: SiNaver },
    { label: "Yandex", icon: FaBuilding },
  
    // Telecom
    { label: "Verizon", icon: FaBuilding },
    { label: "AT&T", icon: FaBuilding },
    { label: "Vodafone", icon: FaBuilding },
  
    // Open Source
    { label: "Apache Foundation", icon: SiApache },
    { label: "Linux Foundation", icon: FaBuilding },
    { label: "GNOME", icon: FaBuilding },

    { label: "WordPress", icon: FaWordpress },
    { label: "OpenAI", icon: SiOpenai },
    { label: "Fastly", icon: SiFastly },
    { label: "Accenture", icon: SiAccenture },
    { label: "Cognizant", icon: SiCognizant },
    { label: "SAP", icon: SiSap },
    { label: "Twilio", icon: SiTwilio },
    { label: "HubSpot", icon: SiHubspot },
    { label: "PagerDuty", icon: SiPagerduty },
    { label: "Elastic", icon: SiElastic },
    { label: "MongoDB", icon: SiMongodb },
    { label: "Snowflake", icon: SiSnowflake },
    { label: "Databricks", icon: SiDatabricks },
    { label: "Cloudera", icon: SiCloudera },
    { label: "Palo Alto Networks", icon: SiPaloaltonetworks },
    { label: "CrowdStrike", icon: FaBuilding },
    { label: "Okta", icon: SiOkta },
    { label: "Zscaler", icon: FaBuilding },
    { label: "F5", icon: SiF5 },
    { label: "Juniper", icon: FaBuilding },
    { label: "Avaya", icon: FaBuilding },
    { label: "Nokia", icon: SiNokia },
    { label: "Ericsson", icon: SiEricsson },
    { label: "Alibaba", icon: FaBuilding },
    { label: "Line", icon: FaBuilding },
    { label: "Mailchimp", icon: SiMailchimp },
    { label: "SendGrid", icon: SiSendgrid },
    { label: "Brave", icon: SiBrave },
    { label: "Opera", icon: SiOpera },
    { label: "Eclipse", icon: SiEclipseide },
    { label: "Sketch", icon: SiSketch },
    { label: "Adobe XD", icon: SiAdobexd },
    { label: "InVision", icon: SiInvision },
    { label: "Jira", icon: SiJira },
    { label: "Confluence", icon: SiConfluence },
    { label: "Asana", icon: SiAsana },
    { label: "Airtable", icon: SiAirtable },
    { label: "Notion", icon: SiNotion },
    { label: "Evernote", icon: SiEvernote },
    { label: "Grammarly", icon: SiGrammarly },
    { label: "Duolingo", icon: SiDuolingo },
    { label: "Udemy", icon: SiUdemy },
    { label: "Coursera", icon: SiCoursera },
    { label: "Khan Academy", icon: SiKhanacademy },
    { label: "Pluralsight", icon: SiPluralsight },
    { label: "LinkedIn", icon: SiLinkedin },
    { label: "Glassdoor", icon: SiGlassdoor },
    { label: "Indeed", icon: SiIndeed },
    { label: "Upwork", icon: SiUpwork },
    { label: "Freelancer", icon: SiFreelancer },
    { label: "Fiverr", icon: SiFiverr },
    { label: "Stack Overflow", icon: SiStackoverflow },
    { label: "Medium", icon: SiMedium },
    { label: "Quora", icon: SiQuora },
    { label: "Hashnode", icon: SiHashnode },
    { label: "Dev.to", icon: SiDevdotto },
    { label: "CodePen", icon: SiCodepen },
    { label: "Replit", icon: SiReplit },
    { label: "Glitch", icon: SiGlitch },
    { label: "CodeSandbox", icon: SiCodesandbox },
    { label: "LeetCode", icon: SiLeetcode },
    { label: "HackerRank", icon: SiHackerrank },
    { label: "Algolia", icon: SiAlgolia },
    { label: "Auth0", icon: SiAuth0 },
    { label: "Firebase", icon: SiFirebase },
    { label: "Supabase", icon: SiSupabase },
    { label: "Hasura", icon: SiHasura },
    { label: "GraphQL", icon: SiGraphql },
    { label: "Nginx", icon: SiNginx },
    { label: "Redis", icon: SiRedis },
    { label: "RabbitMQ", icon: SiRabbitmq },
    { label: "Kafka", icon: FaBuilding },
    { label: "Prometheus", icon: SiPrometheus },
    { label: "Gradle", icon: SiGradle },
    { label: "Maven", icon: FaBuilding },
    { label: "GNU Bash", icon: SiGnubash },
    { label: "Git", icon: SiGit },
    { label: "jQuery", icon: SiJquery },
    { label: "Redux", icon: SiRedux },
    { label: "Webpack", icon: SiWebpack },
    { label: "Babel", icon: SiBabel },
    { label: "ESLint", icon: SiEslint },
    { label: "Prettier", icon: SiPrettier },
    { label: "Jest", icon: SiJest },
    { label: "Cypress", icon: SiCypress },
    { label: "Puppeteer", icon: SiPuppeteer },
    { label: "Storybook", icon: SiStorybook },
    { label: "Loom", icon: SiLoom },
    { label: "Zoom", icon: SiZoom },
    { label: "Tor Browser", icon: SiTorbrowser },
    { label: "ProtonMail", icon: SiProtonmail },
    { label: "Tutanota", icon: SiTutanota },
    { label: "Bitcoin", icon: SiBitcoin },
    { label: "Ethereum", icon: SiEthereum },
    { label: "Ripple", icon: SiRipple },
    { label: "Solana", icon: SiSolana },
    { label: "Chainlink", icon: SiChainlink },
    { label: "Algorand", icon: SiAlgorand },
    { label: "Stellar", icon: SiStellar },
    { label: "Monero", icon: SiMonero },
    { label: "Zcash", icon: SiZcash }
];

export default companies;
