export const SOMETHING_WENT_WRONG = "Something went Wrong !!!";
export const EMAIL_NOT_VERIFIED = "EmailNotVerified";
export const EMAIL_VERIFICATION = "EmailVerification";
export const SUCCESS = "success";
export const FAIL = "fail";
export const ERROR = "error";
export const INVALID_TOKEN_ERROR = "Invalid token";
export const TOKEN_EXPIRED = "Token expired";
export const RESET_PASSWORD = "reset password";
export const EMAIL_VALIDATION = "email validation";
export const LOADING = "loading";
export const TOKEN = "token";
export const VERIFICATION_SUCCESSFULL = "Verification successfull";
export const TOKEN_NOT_FOUND = "Token not found";
export const UNAUTHORIZED = "Unauthorized";
export const UNAUTHENTICATED = "Unauthenticated";
export const INVALID_POST_TYPE= "Invalid post type"
export const INVALID_DIFFICULTY= "Invalid difficulty"
export const INVALID_CATEGORY= "Invalid category"
export const INVALID_SUBCATEGORY= "Invalid subCategory"
export const QUESTION_TYPE="QUESTION"
export const INVALID_POST_ID= "Invalid post ID format"
export const TITLE_MIN_LENGTH= "Title must be at least 3 characters"
export const ANSWER_REQUIRED= "Answer content is required for questions"
export const POST_REQUIRED= "Post content is required"
