const subCategory = {
    javascript: [
      "Async",
      "AsyncAwait",
      "Closures",
      "ControlFlow",
      "DOM",
      "Destructuring",
      "ES6",
      "ErrorHandling",
      "EventLoop",
      "Events",
      "Functional",
      "Libraries",
      "Memory",
      "Modules",
      "OOP",
      "Objects",
      "Performance",
      "Polyfills",
      "PromiseChain",
      "Promises",
      "Regex",
      "SpreadOperator",
      "StateManagement",
      "Testing",
      "TypeCoercion",
      "WebAPIs",
      "Memoization",
      "EventDelegation",
      "Debouncing",
      "Throttling",
    ],
    html: [
      "HTML5",
      "SemanticHTML",
      "Forms",
      "Accessibility",
      "Canvas",
      "SVG",
      "MetaTags",
      "WebStorage",
      "SEO",
      "Iframe",
      "WebSockets",
      "DOMManipulation",
      "ResponsiveDesign",
      "ProgressiveWebApps",
      "WebPerformance",
    ],
    css: [
      "CSS3",
      "Flexbox",
      "Grid",
      "ResponsiveDesign",
      "Animations",
      "Transitions",
      "MediaQueries",
      "Variables",
      "PseudoClasses",
      "PseudoElements",
      "BoxModel",
      "Positioning",
      "ZIndex",
      "Transforms",
      "CSSVariables",
      "BEM",
      "CriticalCSS",
      "CSSGrid",
    ],
    react: [
      "JSX",
      "Components",
      "Props",
      "State",
      "Hooks",
      "ContextAPI",
      "LifecycleMethods",
      "ReactRouter",
      "Redux",
      "useEffect",
      "useState",
      "useMemo",
      "useCallback",
      "EventHandling",
      "Forms",
      "ErrorBoundaries",
      "ReactTestingLibrary",
      "ReactPerformance",
      "VirtualDOM",
      "Reconciliation",
      "Suspense",
      "ServerSideRendering",
      "ReactConcurrentMode",
    ],
  };
  
  
export type SubCategory = keyof typeof subCategory;
export const subCategorySupportedTypes = new Set(Object.keys(subCategory));
export default subCategory